import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'api.dart';
import 'data.dart';

void main()=>runApp(const KpiApp());
class KpiApp extends StatelessWidget {
  const KpiApp({super.key});
  @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'KPI DNS Cao Bằng',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFFE80500),primary:const Color(0xFFE80500)),scaffoldBackgroundColor:const Color(0xFFF5F6F7)),home:const Home());
}

class Home extends StatefulWidget { const Home({super.key}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home> {
  final api=Api(); bool loading=true; String? error; Map<String,AmData> all={}; Map<String,AmTarget> targets={};
  @override void initState(){super.initState();load();}
  Future<void> load() async {setState((){loading=true;error=null;});try{final r=await Future.wait([api.all(),api.targets()]);all=r[0] as Map<String,AmData>;targets=r[1] as Map<String,AmTarget>;}catch(e){error='$e';}if(mounted)setState(()=>loading=false);}
  @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(backgroundColor:const Color(0xFFE80500),foregroundColor:Colors.white,title:const Text('KPI DNS - Viettel Cao Bằng'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Không lấy được dữ liệu\n$error',textAlign:TextAlign.center),const SizedBox(height:12),FilledButton(onPressed:load,child:const Text('Thử lại'))])):_body());
  Widget _title(String s)=>Container(margin:const EdgeInsets.only(top:12),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xFFE80500),borderRadius:BorderRadius.circular(10)),child:Text(s,style:const TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)));
  Widget _body(){final totalKh=List.generate(9,(i)=>all.values.fold<double>(0,(s,a)=>s+a.kh[i]));final totalTh=List.generate(9,(i)=>all.values.fold<double>(0,(s,a)=>s+a.th[i]));final ranks=all.values.toList()..sort((a,b)=>score(b).compareTo(score(a)));return RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(12),children:[_title('1. Tóm tắt kết quả toàn tỉnh'),...List.generate(9,(i)=>Card(child:ListTile(title:Text(metrics[i].name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('TH ${fmt(totalTh[i])} / KH ${fmt(totalKh[i])} ${metrics[i].unit}'),trailing:Text('${(completion(totalTh[i],totalKh[i])*100).toStringAsFixed(1)}%',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900))))),_title('2. Xếp hạng PL05'),...List.generate(ranks.length,(i)=>Card(child:ListTile(leading:CircleAvatar(child:Text('${i+1}')),title:Text(ranks[i].code,style:const TextStyle(fontWeight:FontWeight.w800)),trailing:Text('${score(ranks[i]).toStringAsFixed(1)}/100',style:const TextStyle(fontWeight:FontWeight.w900)),onTap:()=>openAm(ranks[i].code)))),_title('3. 6 Account Manager'),Wrap(spacing:8,runSpacing:8,children:amCodes.map((x)=>FilledButton.tonal(onPressed:()=>openAm(x),child:Text(x))).toList()),const SizedBox(height:28)]));}
  void openAm(String code){final t=targets[code];if(t==null)return;Navigator.push(context,MaterialPageRoute(builder:(_)=>AmPage(code:code,target:t))).then((_)=>load());}
}

class AmPage extends StatefulWidget {const AmPage({super.key,required this.code,required this.target});final String code;final AmTarget target;@override State<AmPage> createState()=>_AmPageState();}
class _AmPageState extends State<AmPage> with SingleTickerProviderStateMixin {
  final api=Api(); late TabController tabs; AmData? data; String? error; bool saving=false; DateTime date=DateTime.now(); final ctrls=List.generate(9,(_)=>TextEditingController());
  @override void initState(){super.initState();tabs=TabController(length:2,vsync:this);load();}
  Future<void> load()async{try{data=await api.one(widget.code);error=null;_fill();}catch(e){error='$e';}if(mounted)setState((){});}
  void _fill(){final d=data;if(d==null)return;final key='${date.year.toString().padLeft(4,'0')}-${date.month.toString().padLeft(2,'0')}-${date.day.toString().padLeft(2,'0')}';final row=d.daily[key];for(var i=0;i<9;i++){final v=row==null?null:row[i];ctrls[i].text=v==null?'':(v==v.roundToDouble()?v.toInt().toString():v.toString());}}
  Future<void> pick()async{final now=DateTime.now();final p=await showDatePicker(context:context,initialDate:date,firstDate:DateTime(now.year,now.month,1),lastDate:DateTime(now.year,now.month+1,0));if(p!=null){date=p;_fill();setState((){});}}
  Future<void> save()async{final vals=<double?>[];for(final c in ctrls){final s=c.text.trim().replaceAll(',','.');if(s.isEmpty){vals.add(null);continue;}final v=double.tryParse(s);if(v==null||v<0){snack('Có giá trị không hợp lệ');return;}vals.add(v);}setState(()=>saving=true);try{await api.save(widget.code,date,vals);await load();snack('Đã lưu và xác minh dữ liệu');}catch(e){snack('Lỗi lưu: $e');}if(mounted)setState(()=>saving=false);}
  void snack(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
  @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(backgroundColor:const Color(0xFFE80500),foregroundColor:Colors.white,title:Text(widget.code),bottom:TabBar(controller:tabs,labelColor:Colors.white,unselectedLabelColor:Colors.white70,tabs:const [Tab(text:'Nhập KQ'),Tab(text:'Tiến độ')])) ,body:TabBarView(controller:tabs,children:[entry(),progress()]));
  Widget entry()=>ListView(padding:const EdgeInsets.all(14),children:[OutlinedButton.icon(onPressed:pick,icon:const Icon(Icons.calendar_month),label:Text(DateFormat('dd/MM/yyyy').format(date))),...List.generate(9,(i)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:TextField(controller:ctrls[i],keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(border:const OutlineInputBorder(),labelText:'${i+1}. ${metrics[i].name} (${metrics[i].unit})',helperText:'Điểm chuẩn ${metrics[i].weight.toStringAsFixed(0)}')))),const SizedBox(height:10),FilledButton.icon(onPressed:saving?null:save,icon:const Icon(Icons.save),label:Text(saving?'Đang lưu...':'Lưu kết quả')),const Padding(padding:EdgeInsets.only(top:10),child:Text('Để trống = chưa nhập; nhập 0 = đã xác nhận không phát sinh.',style:TextStyle(color:Color(0xFFE80500),fontWeight:FontWeight.w800)))]);
  Widget progress(){final a=data;if(error!=null)return Center(child:Text(error!));if(a==null)return const Center(child:CircularProgressIndicator());final now=DateTime.now();final wi=currentWeekIndex(now);final wa=weekActual(a,now);final wp=widget.target.weeks[wi];return ListView(padding:const EdgeInsets.all(12),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[const Text('Điểm PL05 lũy kế tháng',style:TextStyle(fontWeight:FontWeight.w700)),Text('${score(a).toStringAsFixed(1)}/100',style:const TextStyle(fontSize:36,fontWeight:FontWeight.w900,color:Color(0xFFE80500)))]))),Text('Tuần hiện tại: Tuần ${wi+1}',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),...List.generate(9,(i)=>Card(child:ListTile(title:Text(metrics[i].name),subtitle:Text('Tuần: ${fmt(wa[i])}/${fmt(wp[i])} (${(completion(wa[i],wp[i])*100).toStringAsFixed(1)}%)\nTháng: ${fmt(a.th[i])}/${fmt(a.kh[i])} (${(completion(a.th[i],a.kh[i])*100).toStringAsFixed(1)}%)'))))]);}
  @override void dispose(){tabs.dispose();for(final c in ctrls)c.dispose();super.dispose();}
}
String fmt(double v)=>NumberFormat('#,##0.##','vi_VN').format(v);
